name: Migrate PR

on:
  push:
    branches:
      - dev
      - sandbox
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install argparse requests

      - name: Determine Environment
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=env_name::dev"
          elif [[ "${{ github.ref }}" == "refs/heads/sandbox" ]]; then
            echo "::set-output name=env_name::sandbox"
          else
            echo "::set-output name=env_name::main"
          fi
      - name: Print Environment Name
        run: echo "Environment Name: ${{ steps.setenv.outputs.env_name }}"
