name: Migrate PR  

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  migrate:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: pip install argparse requests

      - name: Run Script
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
          DESTINATION_URL: ${{ secrets.DESTINATION_URL }}
        run: python main.py  --source-token ${{ secrets.SOURCE_TOKEN }} --destination-token ${{ secrets.DESTINATION_TOKEN }}
