name: Migrate PR  

on:
  push:
    branches:
      - dev
      - sandbox
      - main
    workflow_dispatch:

jobs:
  migrate:
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/sandbox' && 'sandbox' || 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name:  Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: pip install argparse requests

      - name: Print Environment Name
        run: echo ${{ job.environment.name }} 
    #- name: Run Script
    #  run: python main.py --source-url ${{ secrets.SOURCE_URL}} --destination-url ${{ secrets.DESTINATION_URL }} --source-token ${{ secrets.SOURCE_TOKEN }} --destination-token ${{ secrets.DESTINATION_TOKEN }}

