name: Migrate PR  

on:
  push:
    branches:
      - dev
      - sandbox
      - main
    workflow_dispatch:

jobs:
  migrate:
    strategy:
      matrix:
        include:
          - branch: dev
            environment: dev
          - branch: sandbox
            environment: sandbox
          - branch: main
            environment: main
    if: github.ref == 'refs/heads/${{ matrix.branch }}'
    environment: 
      name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name:  Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: pip install argparse requests

      - name: Print Environment Name
        run: echo "Environment Name: ${{ matrix.environment }}"

      - name: Run Script
        run: python main.py --source-url ${{ secrets.SOURCE_URL}} --destination-url ${{ secrets.DESTINATION_URL }} --source-token ${{ secrets.SOURCE_TOKEN }} --destination-token ${{ secrets.DESTINATION_TOKEN }}

